import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class IntrinsicValue {
	static double opCashminus2;
	static double opCashminus1;
	static double opCashCurrent;
	static double capEx2;
	static double capEx1;
	static double capExCurrent;
	static double growthRate1;
	static double growthRate2;
	static double a; // average operating cash for last three years
	static double b; // average capital expenditure for last three years
	static double fifthCash;
	static double tenthCash;
	static double terminalValue;
	static double terminalGrowthRate;
	static double discountRate;
	static double sumNpv; // sum of all npv of fcf till 10 th year
	static double shareholderCash; // the cash shareholder has

	public static void averageOperatingCashFlow() {
		System.out.println("Enter the last three years Operating Cash: ");
		Scanner s = new Scanner(System.in);
		System.out.println("Enter 2 years before Operating Cash");
		opCashminus2 = s.nextDouble();
		System.out.println("Enter last year  Operating Cash");
		opCashminus1 = s.nextDouble();
		System.out.println("Enter current year  Operating Cash");
		opCashCurrent = s.nextDouble();
		a = (opCashminus2 + opCashminus1 + opCashCurrent) / 3;
		s.close();

	}

	public static void averageCapitalExpenditure() {
		System.out.println("Enter the last three years Capital Expenditure: ");
		Scanner s = new Scanner(System.in);

		System.out.println("Enter 2 years before Capital Expenditure: ");
		capEx2 = s.nextDouble();
		System.out.println("Enter last year Capital Expenditure: ");
		capEx1 = s.nextDouble();
		System.out.println("Enter current year Capital Expenditure: ");
		capExCurrent = s.nextDouble();
		b = (capEx2 + capEx1 + capExCurrent) / 3;
		s.close();

	}

	public static void rate() {
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter the growth rate for first five years");
		growthRate1 = sc.nextDouble();
		System.out.println("Enter the growth rate for first last years");
		growthRate2 = sc.nextDouble();
		System.out.println("Enter the terminal growth rate for first five years");
		terminalGrowthRate = sc.nextDouble();
		System.out.println("Enter the discount  rate for first five years ");
		discountRate = sc.nextDouble();

	}

	public static void FCF() {
		System.out.println("The future cash flow is as follows: ");
		ArrayList<Double> list = new ArrayList<>();

		for (int i = 1; i <= 5; i++) {
			double sum = a * Math.pow((1 + (growthRate1 / 100)), i);
			System.out.println("The future cash flow for " + i + "th year is " + sum);
			list.add(sum);
		}

		fifthCash = a * Math.pow((1 + (growthRate1 / 100)), 5);

		for (int i = 6; i <= 10; i++) {
			double sum1 = fifthCash * Math.pow((1 + (growthRate2 / 100)), i);
			System.out.println("The future cash flow for " + i + "th year is " + sum1);
			list.add((i - 1), sum1);
		}
		System.out.println(list);
		tenthCash = a * Math.pow((1 + (growthRate2 / 100)), 10);

		terminalValue = tenthCash * (1 + (terminalGrowthRate / 100)) / ((discountRate - terminalGrowthRate) / 100);

		// calculation of npv of future cash flow
		for (int i = 1; i <= 10; i++) {
			double npv = list.get(i - 1) / Math.pow(1 + discountRate, i);
			System.out.println("the npv of each till 10th is: " + npv);
			sumNpv += npv;
		}
		double terminalNpv = terminalValue / Math.pow(1 + (discountRate / 100), 10);
		shareholderCash = terminalNpv + sumNpv;
		System.out.println(
				"Standing today and looking into future ,the expected total free cash flow to be generated by company is: "
						+ shareholderCash);
	}

	public static void main(String[] args) {

//		averageOperatingCashFlow();
//		averageCapitalExpenditure();
//		rate();

		FCF();

	}

}
